#!/bin/sh

# defaults for build
BUILD_DIR=build
APP_NAME=ruuvitag-demo
EXTRA_CMAKE_PARAMS=

[ ! -z "$1" ] && APP_NAME=$1
[ ! -z "$2" ] && EXTRA_CMAKE_PARAMS=$2

if [ -d $BUILD_DIR ] ; then
	echo "build directory already exists."
	exit 1
fi

if [ ! -d app/$APP_NAME ] ; then
	echo "app" $APP_NAME "don't exist!"
	exit 1
fi

mkdir $BUILD_DIR; cd $BUILD_DIR
cmake $EXTRA_CMAKE_PARAMS -DAPP_NAME=$APP_NAME -C../default-config.cmake ..
