/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "ble_tps.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Tx Power packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Tx Power packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_TX_POWER_LEVEL_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Tx Power Level. */ 

/**@brief Function for encoding Tx Power Level.
 *
 * @param[in]   p_tx_power_level              Tx Power Level characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t tx_power_level_encode(ble_tps_tx_power_level_t * p_tx_power_level, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_tx_power_level->tx_power;
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_tps       Tx Power Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_tps_t * p_tps, ble_evt_t * p_ble_evt)
{
    p_tps->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_tps       Tx Power Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_tps_t * p_tps, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_tps->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_tps       Tx Power Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_tps_t * p_tps, ble_gatts_evt_write_t * p_ble_evt)
{
    
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_tps_t * p_tps, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_tps       Tx Power Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_tps_on_ble_evt(ble_tps_t * p_tps, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_tps, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_tps, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_tps, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_tps, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Tx Power. */
uint32_t ble_tps_init(ble_tps_t * p_tps, const ble_tps_init_t * p_tps_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_tps->evt_handler = p_tps_init->evt_handler;
    p_tps->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    BLE_UUID_BLE_ASSIGN(ble_uuid, 0x1804);
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_tps->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Tx Power Level characteristic
    ble_tps_tx_power_level_t tx_power_level_initial_value = p_tps_init->ble_tps_tx_power_level_initial_value; 

    uint8_t tx_power_level_encoded_value[MAX_TX_POWER_LEVEL_LEN];
    ble_add_char_params_t add_tx_power_level_params;
    memset(&add_tx_power_level_params, 0, sizeof(add_tx_power_level_params));
    
    add_tx_power_level_params.uuid                = 0x2A07; 
    add_tx_power_level_params.max_len             = MAX_TX_POWER_LEVEL_LEN;
    add_tx_power_level_params.init_len            = tx_power_level_encode(&tx_power_level_initial_value, tx_power_level_encoded_value);
    add_tx_power_level_params.p_init_value        = tx_power_level_encoded_value; 
    add_tx_power_level_params.char_props.read     = 1; 
    add_tx_power_level_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_tx_power_level_params.is_var_len          = 1; 

    err_code = characteristic_add(p_tps->service_handle, &add_tx_power_level_params, &(p_tps->tx_power_level_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Tx Power Level. */
uint32_t ble_tps_tx_power_level_set(ble_tps_t * p_tps, ble_tps_tx_power_level_t * p_tx_power_level)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_TX_POWER_LEVEL_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = tx_power_level_encode(p_tx_power_level, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_tps->conn_handle, p_tps->tx_power_level_handles.value_handle, &gatts_value);
}

