/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#ifndef BLE_ACCELERATION_SERVICE_H__
#define BLE_ACCELERATION_SERVICE_H__

#include <stdint.h>
#include <stdbool.h>
#include "ble.h"
#include "ble_srv_common.h"
#include "app_util_bds.h"



/**@brief Acceleration service event type. */
typedef enum
{ 
    BLE_ACCELERATION_SERVICE_IMU_DATA_EVT_NOTIFICATION_ENABLED,  /**< IMU Data value notification enabled event. */
    BLE_ACCELERATION_SERVICE_IMU_DATA_EVT_NOTIFICATION_DISABLED, /**< IMU Data value notification disabled event. */
    BLE_ACCELERATION_SERVICE_IMU_DATA_EVT_CCCD_WRITE, /**< IMU Data CCCD write event. */
} ble_acceleration_service_evt_type_t;

// Forward declaration of the ble_acceleration_service_t type.
typedef struct ble_acceleration_service_s ble_acceleration_service_t;








/**@brief IMU Data structure. */
typedef struct
{
    uint8_array_t imu_array;
} ble_acceleration_service_imu_data_t;

/**@brief Acceleration service Service event. */
typedef struct
{
    ble_acceleration_service_evt_type_t evt_type;    /**< Type of event. */
    union {
        uint16_t cccd_value; /**< Holds decoded data in Notify and Indicate event handler. */
    } params;
} ble_acceleration_service_evt_t;

/**@brief Acceleration service Service event handler type. */
typedef void (*ble_acceleration_service_evt_handler_t) (ble_acceleration_service_t * p_acceleration_service, ble_acceleration_service_evt_t * p_evt);

/**@brief Acceleration service Service init structure. This contains all options and data needed for initialization of the service */
typedef struct
{
    ble_acceleration_service_evt_handler_t     evt_handler; /**< Event handler to be called for handling events in the Acceleration service Service. */
    ble_acceleration_service_imu_data_t ble_acceleration_service_imu_data_initial_value; /**< If not NULL, initial value of the IMU Data characteristic. */ 
} ble_acceleration_service_init_t;

/**@brief Acceleration service Service structure. This contains various status information for the service.*/
struct ble_acceleration_service_s
{
    ble_acceleration_service_evt_handler_t evt_handler; /**< Event handler to be called for handling events in the Acceleration service Service. */
    uint16_t service_handle; /**< Handle of Acceleration service Service (as provided by the BLE stack). */
    ble_gatts_char_handles_t imu_data_handles; /**< Handles related to the IMU Data characteristic. */
    uint16_t conn_handle; /**< Handle of the current connection (as provided by the BLE stack, is BLE_CONN_HANDLE_INVALID if not in a connection). */
};

/**@brief Function for initializing the Acceleration service.
 *
 * @param[out]  p_acceleration_service       Acceleration service Service structure. This structure will have to be supplied by
 *                          the application. It will be initialized by this function, and will later
 *                          be used to identify this particular service instance.
 * @param[in]   p_acceleration_service_init  Information needed to initialize the service.
 *
 * @return      NRF_SUCCESS on successful initialization of service, otherwise an error code.
 */
uint32_t ble_acceleration_service_init(ble_acceleration_service_t * p_acceleration_service, const ble_acceleration_service_init_t * p_acceleration_service_init);

/**@brief Function for handling the Application's BLE Stack events.*/
void ble_acceleration_service_on_ble_evt(ble_acceleration_service_t * p_acceleration_service, ble_evt_t * p_ble_evt);

/**@brief Function for setting the IMU Data.
 *
 * @details Sets a new value of the IMU Data characteristic. The new value will be sent
 *          to the client the next time the client reads the IMU Data characteristic.
 *          This function is only generated if the characteristic's Read property is not 'Excluded'.
 *
 * @param[in]   p_acceleration_service                 Acceleration service Service structure.
 * @param[in]   p_imu_data  New IMU Data.
 *
 * @return      NRF_SUCCESS on success, otherwise an error code.
 */
uint32_t ble_acceleration_service_imu_data_set(ble_acceleration_service_t * p_acceleration_service, ble_acceleration_service_imu_data_t * p_imu_data);

/**@brief Function for sending the IMU Data.
 *
 * @details The application calls this function after having performed a imu data.
 *          The imu data data is encoded and sent to the client.
 *          This function is only generated if the characteristic's Notify or Indicate property is not 'Excluded'.
 *
 * @param[in]   p_acceleration_service                    Acceleration service Service structure.
 * @param[in]   p_imu_data               New imu data.
 *
 * @return      NRF_SUCCESS on success, otherwise an error code.
 */
uint32_t ble_acceleration_service_imu_data_send(ble_acceleration_service_t * p_acceleration_service, ble_acceleration_service_imu_data_t * p_imu_data);

#endif //_BLE_ACCELERATION_SERVICE_H__
