/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "ble_ess.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Environmental Sensing packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Environmental Sensing packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_PRESSURE_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Pressure. */ 
#define MAX_TEMPERATURE_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Temperature. */ 
#define MAX_HUMIDITY_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Humidity. */ 
#define MAX_BAROMETRIC_PRESSURE_TREND_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Barometric Pressure Trend. */ 

/**@brief Function for encoding Pressure.
 *
 * @param[in]   p_pressure              Pressure characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t pressure_encode(ble_ess_pressure_t * p_pressure, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint32_encode(&p_pressure->pressure, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for encoding Temperature.
 *
 * @param[in]   p_temperature              Temperature characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t temperature_encode(ble_ess_temperature_t * p_temperature, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_int16_encode(&p_temperature->temperature, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for encoding Humidity.
 *
 * @param[in]   p_humidity              Humidity characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t humidity_encode(ble_ess_humidity_t * p_humidity, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint16_encode(&p_humidity->humidity, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Humidity.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t humidity_decode(uint8_t data_len, uint8_t * p_data, ble_ess_humidity_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->humidity); 

    return pos;
} 
/**@brief Function for encoding Barometric Pressure Trend.
 *
 * @param[in]   p_barometric_pressure_trend              Barometric Pressure Trend structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t barometric_pressure_trend_barometric_pressure_trend_encode(barometric_pressure_trend_barometric_pressure_trend_t * p_barometric_pressure_trend, uint8_t * encoded_buffer)
{
    uint8_t barometric_pressure_trend;
    barometric_pressure_trend = p_barometric_pressure_trend->barometric_pressure_trend;
    encoded_buffer[0] = barometric_pressure_trend;
    return 1; 
}

/**@brief Function for encoding Barometric Pressure Trend.
 *
 * @param[in]   p_barometric_pressure_trend              Barometric Pressure Trend characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t barometric_pressure_trend_encode(ble_ess_barometric_pressure_trend_t * p_barometric_pressure_trend, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += barometric_pressure_trend_barometric_pressure_trend_encode(&p_barometric_pressure_trend->barometric_pressure_trend, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_ess       Environmental Sensing Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_ess_t * p_ess, ble_evt_t * p_ble_evt)
{
    p_ess->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_ess       Environmental Sensing Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_ess_t * p_ess, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_ess->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_ess       Environmental Sensing Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_ess_t * p_ess, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_ess->pressure_handles.cccd_handle)
    {
        if(p_ess->evt_handler != NULL)
        {
            ble_ess_evt_t evt;
            evt.evt_type = BLE_ESS_PRESSURE_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_ess->evt_handler(p_ess, &evt);
        }
    } 
    if(p_ble_evt->handle == p_ess->temperature_handles.cccd_handle)
    {
        if(p_ess->evt_handler != NULL)
        {
            ble_ess_evt_t evt;
            evt.evt_type = BLE_ESS_TEMPERATURE_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_ess->evt_handler(p_ess, &evt);
        }
    } 
    if(p_ble_evt->handle == p_ess->humidity_handles.cccd_handle)
    {
        if(p_ess->evt_handler != NULL)
        {
            ble_ess_evt_t evt;
            evt.evt_type = BLE_ESS_HUMIDITY_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_ess->evt_handler(p_ess, &evt);
        }
    } 
    if(p_ble_evt->handle == p_ess->humidity_handles.value_handle)
    {
        if(p_ess->evt_handler != NULL)
        {
            ble_ess_evt_t evt;
            evt.evt_type = BLE_ESS_HUMIDITY_EVT_WRITE;
            humidity_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.humidity);
            p_ess->evt_handler(p_ess, &evt);
        }
    }
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_ess_t * p_ess, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_ess->humidity_handles.value_handle)
            {
                on_write(p_ess, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_ess       Environmental Sensing Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_ess_on_ble_evt(ble_ess_t * p_ess, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_ess, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_ess, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_ess, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_ess, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Environmental Sensing. */
uint32_t ble_ess_init(ble_ess_t * p_ess, const ble_ess_init_t * p_ess_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_ess->evt_handler = p_ess_init->evt_handler;
    p_ess->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    /*ble_uuid128_t bds_base_uuid = {{0xC7, 0xE9, 0x01, 0x22, 0x16, 0x0C, 0xB8, 0x9B, 0xE5, 0x45, 0x7D, 0x1D, 0x00, 0x00, 0x67, 0xAE}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x79C9;*/
    
    // Use standard ESS 16-bit UUID
    BLE_UUID_BLE_ASSIGN(ble_uuid, 0x181A);
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_ess->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Pressure characteristic
    ble_ess_pressure_t pressure_initial_value = p_ess_init->ble_ess_pressure_initial_value; 
    p_ess->is_pressure_notify_supported = p_ess_init->is_pressure_notify_supported;

    uint8_t pressure_encoded_value[MAX_PRESSURE_LEN];
    ble_add_char_params_t add_pressure_params;
    memset(&add_pressure_params, 0, sizeof(add_pressure_params));
    
    add_pressure_params.uuid                = 0x2A6D; 
    add_pressure_params.max_len             = MAX_PRESSURE_LEN;
    add_pressure_params.init_len            = pressure_encode(&pressure_initial_value, pressure_encoded_value);
    add_pressure_params.p_init_value        = pressure_encoded_value; 
    add_pressure_params.char_props.notify   = p_ess->is_pressure_notify_supported; 
    add_pressure_params.char_props.read     = 1; 
    add_pressure_params.read_access         = SEC_OPEN; 
    add_pressure_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_pressure_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ess->service_handle, &add_pressure_params, &(p_ess->pressure_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Temperature characteristic
    ble_ess_temperature_t temperature_initial_value = p_ess_init->ble_ess_temperature_initial_value; 
    p_ess->is_temperature_notify_supported = p_ess_init->is_temperature_notify_supported;

    uint8_t temperature_encoded_value[MAX_TEMPERATURE_LEN];
    ble_add_char_params_t add_temperature_params;
    memset(&add_temperature_params, 0, sizeof(add_temperature_params));
    
    add_temperature_params.uuid                = 0x2A6E; 
    add_temperature_params.max_len             = MAX_TEMPERATURE_LEN;
    add_temperature_params.init_len            = temperature_encode(&temperature_initial_value, temperature_encoded_value);
    add_temperature_params.p_init_value        = temperature_encoded_value; 
    add_temperature_params.char_props.notify   = p_ess->is_temperature_notify_supported; 
    add_temperature_params.char_props.read     = 1; 
    add_temperature_params.read_access         = SEC_OPEN; 
    add_temperature_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_temperature_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ess->service_handle, &add_temperature_params, &(p_ess->temperature_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Humidity characteristic
    ble_ess_humidity_t humidity_initial_value = p_ess_init->ble_ess_humidity_initial_value; 

    uint8_t humidity_encoded_value[MAX_HUMIDITY_LEN];
    ble_add_char_params_t add_humidity_params;
    memset(&add_humidity_params, 0, sizeof(add_humidity_params));
    
    add_humidity_params.uuid                = 0x2A6F; 
    add_humidity_params.max_len             = MAX_HUMIDITY_LEN;
    add_humidity_params.init_len            = humidity_encode(&humidity_initial_value, humidity_encoded_value);
    add_humidity_params.p_init_value        = humidity_encoded_value; 
    add_humidity_params.char_props.notify   = 1; 
    add_humidity_params.char_props.read     = 1; 
    add_humidity_params.read_access         = SEC_OPEN; 
    add_humidity_params.char_props.write    = 1; 
    add_humidity_params.write_access        = SEC_OPEN; 
    add_humidity_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_humidity_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ess->service_handle, &add_humidity_params, &(p_ess->humidity_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Barometric Pressure Trend characteristic
    ble_ess_barometric_pressure_trend_t barometric_pressure_trend_initial_value = p_ess_init->ble_ess_barometric_pressure_trend_initial_value; 

    uint8_t barometric_pressure_trend_encoded_value[MAX_BAROMETRIC_PRESSURE_TREND_LEN];
    ble_add_char_params_t add_barometric_pressure_trend_params;
    memset(&add_barometric_pressure_trend_params, 0, sizeof(add_barometric_pressure_trend_params));
    
    add_barometric_pressure_trend_params.uuid                = 0x2AA3; 
    add_barometric_pressure_trend_params.max_len             = MAX_BAROMETRIC_PRESSURE_TREND_LEN;
    add_barometric_pressure_trend_params.init_len            = barometric_pressure_trend_encode(&barometric_pressure_trend_initial_value, barometric_pressure_trend_encoded_value);
    add_barometric_pressure_trend_params.p_init_value        = barometric_pressure_trend_encoded_value; 
    add_barometric_pressure_trend_params.char_props.read     = 1; 
    add_barometric_pressure_trend_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_barometric_pressure_trend_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ess->service_handle, &add_barometric_pressure_trend_params, &(p_ess->barometric_pressure_trend_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Pressure. */
uint32_t ble_ess_pressure_set(ble_ess_t * p_ess, ble_ess_pressure_t * p_pressure)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_PRESSURE_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = pressure_encode(p_pressure, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_ess->conn_handle, p_ess->pressure_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Pressure. */
uint32_t ble_ess_pressure_send(ble_ess_t * p_ess, ble_ess_pressure_t * p_pressure)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_ess->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_PRESSURE_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = pressure_encode(p_pressure, encoded_value);
        hvx_params.handle = p_ess->pressure_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_ess->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for setting the Temperature. */
uint32_t ble_ess_temperature_set(ble_ess_t * p_ess, ble_ess_temperature_t * p_temperature)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_TEMPERATURE_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = temperature_encode(p_temperature, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_ess->conn_handle, p_ess->temperature_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Temperature. */
uint32_t ble_ess_temperature_send(ble_ess_t * p_ess, ble_ess_temperature_t * p_temperature)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_ess->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_TEMPERATURE_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = temperature_encode(p_temperature, encoded_value);
        hvx_params.handle = p_ess->temperature_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_ess->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for setting the Humidity. */
uint32_t ble_ess_humidity_set(ble_ess_t * p_ess, ble_ess_humidity_t * p_humidity)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_HUMIDITY_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = humidity_encode(p_humidity, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_ess->conn_handle, p_ess->humidity_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Humidity. */
uint32_t ble_ess_humidity_send(ble_ess_t * p_ess, ble_ess_humidity_t * p_humidity)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_ess->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_HUMIDITY_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = humidity_encode(p_humidity, encoded_value);
        hvx_params.handle = p_ess->humidity_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_ess->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for setting the Barometric Pressure Trend. */
uint32_t ble_ess_barometric_pressure_trend_set(ble_ess_t * p_ess, ble_ess_barometric_pressure_trend_t * p_barometric_pressure_trend)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_BAROMETRIC_PRESSURE_TREND_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = barometric_pressure_trend_encode(p_barometric_pressure_trend, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_ess->conn_handle, p_ess->barometric_pressure_trend_handles.value_handle, &gatts_value);
}


