/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "ble_nordic_uart_service.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Nordic UART Service packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Nordic UART Service packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_TX_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted TX. */ 
#define MAX_RX_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted RX. */ 

/**@brief Function for encoding TX.
 *
 * @param[in]   p_tx              TX characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t tx_encode(ble_nordic_uart_service_tx_t * p_tx, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_tx->tx, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding TX.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t tx_decode(uint8_t data_len, uint8_t * p_data, ble_nordic_uart_service_tx_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->tx); 

    return pos;
} 
/**@brief Function for encoding RX.
 *
 * @param[in]   p_rx              RX characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t rx_encode(ble_nordic_uart_service_rx_t * p_rx, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_rx->rx, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_nordic_uart_service       Nordic UART Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_nordic_uart_service_t * p_nordic_uart_service, ble_evt_t * p_ble_evt)
{
    p_nordic_uart_service->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_nordic_uart_service       Nordic UART Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_nordic_uart_service_t * p_nordic_uart_service, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_nordic_uart_service->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_nordic_uart_service       Nordic UART Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_nordic_uart_service_t * p_nordic_uart_service, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_nordic_uart_service->tx_handles.value_handle)
    {
        if(p_nordic_uart_service->evt_handler != NULL)
        {
            ble_nordic_uart_service_evt_t evt;
            evt.evt_type = BLE_NORDIC_UART_SERVICE_TX_EVT_WRITE;
            tx_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.tx);
            p_nordic_uart_service->evt_handler(p_nordic_uart_service, &evt);
        }
    }
    if(p_ble_evt->handle == p_nordic_uart_service->rx_handles.cccd_handle)
    {
        if(p_nordic_uart_service->evt_handler != NULL)
        {
            ble_nordic_uart_service_evt_t evt;
            evt.evt_type = BLE_NORDIC_UART_SERVICE_RX_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_nordic_uart_service->evt_handler(p_nordic_uart_service, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_nordic_uart_service_t * p_nordic_uart_service, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_nordic_uart_service->tx_handles.value_handle)
            {
                on_write(p_nordic_uart_service, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_nordic_uart_service       Nordic UART Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_nordic_uart_service_on_ble_evt(ble_nordic_uart_service_t * p_nordic_uart_service, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_nordic_uart_service, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_nordic_uart_service, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_nordic_uart_service, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_nordic_uart_service, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Nordic UART Service. */
uint32_t ble_nordic_uart_service_init(ble_nordic_uart_service_t * p_nordic_uart_service, const ble_nordic_uart_service_init_t * p_nordic_uart_service_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_nordic_uart_service->evt_handler = p_nordic_uart_service_init->evt_handler;
    p_nordic_uart_service->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x9E, 0xCA, 0xDC, 0x24, 0x0E, 0xE5, 0xA9, 0xE0, 0x93, 0xF3, 0xA3, 0xB5, 0x00, 0x00, 0x40, 0x6E}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x0001;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_nordic_uart_service->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add TX characteristic
    ble_nordic_uart_service_tx_t tx_initial_value = p_nordic_uart_service_init->ble_nordic_uart_service_tx_initial_value; 

    uint8_t tx_encoded_value[MAX_TX_LEN];
    ble_add_char_params_t add_tx_params;
    memset(&add_tx_params, 0, sizeof(add_tx_params));
    
    add_tx_params.uuid                = 0x0002; 
    add_tx_params.max_len             = MAX_TX_LEN;
    add_tx_params.init_len            = tx_encode(&tx_initial_value, tx_encoded_value);
    add_tx_params.p_init_value        = tx_encoded_value; 
    add_tx_params.char_props.write    = 1; 
    add_tx_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_tx_params.is_var_len          = 1; 

    err_code = characteristic_add(p_nordic_uart_service->service_handle, &add_tx_params, &(p_nordic_uart_service->tx_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add RX characteristic
    ble_nordic_uart_service_rx_t rx_initial_value = p_nordic_uart_service_init->ble_nordic_uart_service_rx_initial_value; 

    uint8_t rx_encoded_value[MAX_RX_LEN];
    ble_add_char_params_t add_rx_params;
    memset(&add_rx_params, 0, sizeof(add_rx_params));
    
    add_rx_params.uuid                = 0x0003; 
    add_rx_params.max_len             = MAX_RX_LEN;
    add_rx_params.init_len            = rx_encode(&rx_initial_value, rx_encoded_value);
    add_rx_params.p_init_value        = rx_encoded_value; 
    add_rx_params.char_props.notify   = 1; 
    add_rx_params.char_props.read     = 1; 
    add_rx_params.read_access         = SEC_OPEN; 
    add_rx_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_rx_params.is_var_len          = 1; 

    err_code = characteristic_add(p_nordic_uart_service->service_handle, &add_rx_params, &(p_nordic_uart_service->rx_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the RX. */
uint32_t ble_nordic_uart_service_rx_set(ble_nordic_uart_service_t * p_nordic_uart_service, ble_nordic_uart_service_rx_t * p_rx)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_RX_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = rx_encode(p_rx, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_nordic_uart_service->conn_handle, p_nordic_uart_service->rx_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the RX. */
uint32_t ble_nordic_uart_service_rx_send(ble_nordic_uart_service_t * p_nordic_uart_service, ble_nordic_uart_service_rx_t * p_rx)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_nordic_uart_service->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_RX_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = rx_encode(p_rx, encoded_value);
        hvx_params.handle = p_nordic_uart_service->rx_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_nordic_uart_service->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

