#ifndef MAM_H
#define MAM_H

// Header to libiota_mam_bindings

/** @brief Create Masked Authentication Messaging (MAM) message
 * 
 *  @details Given seed and a message, returns ...
 *
 *
 *  @param c_seed IOTA seed generated by IOTA c library
 *  @param c_message, payload, length ??? ... ??? bytes
 *  @param start ?
 *  @param size  ?
 *  @param index ?
 *  @param next_start ?
 *  @param next_count ?
 *  @param security Security level, 1, 2 or 3 3 being highest(?)
 *
 *  @return ? (what allocates/deallocates?)
 */
const uint8_t* mam_create(const char* c_seed,
                          const char* c_message,
                          size_t start,
                          size_t size,
                          size_t index,
                          size_t next_start,
                          size_t next_count,
                          uint8_t security
);
#endif
