#include "application_service_if.h"
#include <stdint.h>

#include "ble_nus.h"

#include "ble_bulk_transfer.h"

#define NRF_LOG_MODULE_NAME "SERVICE"
#include "nrf_log.h"
#include "nrf_log_ctrl.h"

ble_nus_t m_nus;     /**< Structure to identify the Nordic UART Service. */

static void nus_data_handler(ble_nus_t * p_nus, uint8_t * p_data, uint16_t length)
{
  NRF_LOG_INFO("Received %s\r\n", (uint32_t)p_data);
}

/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t application_services_init(void)
{

    uint32_t       err_code;
    ble_nus_init_t nus_init;

    memset(&nus_init, 0, sizeof(nus_init));

    nus_init.data_handler = nus_data_handler;

    err_code = ble_nus_init(&m_nus, &nus_init);
    APP_ERROR_CHECK(err_code);
    
    //Setup BLE bulk data transfer pointer
    ble_bulk_set_nus(&m_nus);
  
    return NRF_SUCCESS;
}

/** Return pointer to BLE nus service **/
ble_nus_t* get_nus(void)
{
  return &m_nus;
}
