#include "application_service_if.h"
#include <stdint.h>

#include "nrf_ble_es.h"
#include "bsp.h"
#include "bsp_board_config.h"

#define NRF_LOG_MODULE_NAME "SERVICE"
#include "nrf_log.h"
#include "nrf_log_ctrl.h"

/**@brief Function for handling Eddystone events.
 *
 * @param[in] evt Eddystone event to handle.
 */
static void on_es_evt(nrf_ble_es_evt_t evt)
{
    switch(evt)
    {
        case NRF_BLE_ES_EVT_ADVERTISEMENT_SENT:
            //bsp_board_led_invert(NON_CONNECTABLE_ADV_LED_PIN);
            break;
        
        case NRF_BLE_ES_EVT_CONNECTABLE_ADV_STARTED:
            bsp_board_led_on(CONNECTABLE_ADV_LED_PIN);
            break;

        default:
            break;
    }
}

/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t application_services_init(void)
{
    nrf_ble_es_init(on_es_evt);
    return NRF_SUCCESS;
}