#ifndef EVENT_HANDLERS_H
#define EVENT_HANDLERS_H

#include "fds.h"
#include "fstorage.h"
#include "ble.h"
#include "ble_hci.h"
#include "ble_srv_common.h"
#include "ble_advdata.h"
#include "ble_advertising.h"
#include "ble_conn_params.h"
#include "ble_conn_state.h"
#include "bsp.h"
#include "bsp_btn_ble.h"
#include "peer_manager.h"
#include "nrf_ble_qwr.h"
#include "nrf_drv_csense.h"

#include "application_service_if.h"

/**@brief Function for handling File Data Storage events.
 *
 * @param[in] p_evt  Peer Manager event.
 * @param[in] cmd
 */
void fds_evt_handler(fds_evt_t const * const p_evt);

/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
void bsp_event_handler(bsp_event_t event);

void sys_evt_dispatch(uint32_t sys_evt);

#endif
