#include "event_handlers.h"

#include <stdint.h>
#include <string.h>

#define NRF_LOG_MODULE_NAME "EVENT_HANDLER"
//#define NRF_LOG_LEVEL 4
#include "nrf_log.h"
#include "nrf_log_ctrl.h"

#include "ble.h"
#include "bsp.h"

/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
void bsp_event_handler(bsp_event_t event)
{

}
