#ifndef BLUETOOTH_APP_CONFIG
#define BLUETOOTH_APP_CONFIG

#define APPLICATION_DEVICE_NAME "Ruuvi"
#define APP_DEVICE_NAME APPLICATION_DEVICE_NAME
#define APPLICATION_DEVICE_NAME_LENGTH 5
#define APP_DEVICE_NAME_LENGTH APPLICATION_DEVICE_NAME_LENGTH

#endif