#ifndef MAM_H
#define MAM_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

// Header to libiota_mam_bindings.a

// Magic numbers given by https://github.com/th0br0/
#define MAM_START 1
#define MAM_COUNT 2
#define MAM_INDEX 1
#define MAM_NEXT_START (MAM_START + MAM_COUNT)
#define MAM_NEXT_COUNT 1
#define MAM_SECURITY 1
#define MAM_ROOT_LENGTH 81

/** @brief Create Masked Authentication Messaging (MAM) message
 * 
 *  @details Given seed and a message, returns ...
 *
 *
 *  @param c_seed IOTA seed generated by IOTA c library
 *  @param c_message, payload, length ??? ... ??? bytes
 *  @param start ?
 *  @param size  ?
 *  @param index ?
 *  @param next_start ?
 *  @param next_count ?
 *  @param security Security level, 1, 2 or 3 3 being highest(?)
 *
 *  @return ? (what allocates/deallocates?)
 */
const char* mam_create(const char* c_seed,
                          const char* c_message,
                          size_t start,
                          size_t size,
                          size_t index,
                          size_t next_start,
                          size_t next_count,
                          uint8_t security
);

/**
 *  ?
 */
const char* mam_parse(const char* masked_payload, const char* root, size_t index);

#endif
